/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: ARCTIC  WOLVES™ (https://sketchfab.com/arctic.wolves)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/planet-of-phoenix-bbe2737a863445f7bb2a6901d10b090a
Title: Planet Of Phoenix
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber';

export default function Cube(props) {
    const planetRef = useRef();
    useFrame(() => {
      
      planetRef.current.rotation.y += 0.0005;
    });

  const { nodes, materials } = useGLTF('/models/planet_of_phoenix.glb')
  return (
    <group {...props} ref={planetRef} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.078}>
        <group rotation={[-Math.PI, 0, 0]} scale={0.001}>
          <group scale={10000}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Phoenix_LOD0__0.geometry}
              material={materials['Scene_-_Root']}
              position={[0, 0, -22.361]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}
useGLTF.preload('/models/planet_of_phoenix.glb')