/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: xenadus (https://sketchfab.com/xenadus)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/react-logo-76174ceeba96487f9863f974636f641e
Title: React logo
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import gsap from 'gsap'
import { useGSAP } from '@gsap/react'

export function ReactLogo(props) {
  const { nodes, materials } = useGLTF('/models/react.glb')
  const reactLogoRef = useRef();
  useGSAP(()=>{
    gsap.to(reactLogoRef.current.position,{
        y:reactLogoRef.current.position.y+0.5,
        duration:1.5,
        repeat:-1,
        yoyo:true,
    })
  })
  

  return (
    <group {...props} ref={reactLogoRef} dispose={null}>
      <group scale={0.2}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['React-Logo_Material002_0'].geometry}
          material={materials['Material.002']}
          position={[0, 7.935, 18.102]}
          rotation={[0, 0, -Math.PI / 2]}
          
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/react.glb')
